/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ul;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Film;
import services.FilmService;

/**
 *
 * @author Original Computer
 */
public class FilmForm extends javax.swing.JInternalFrame {

    FilmService fs = null;
    DefaultTableModel model = null;
    static int id;

    /**
     * Creates new form FilmForm
     */
    public FilmForm() {
        initComponents();
        applyFilmTheme();
        addHoverEffect();

        this.setTitle("Gestion des films");
        fs = new FilmService();
        model = (DefaultTableModel) listeFilms.getModel();
        load();
    }

    public void load() {
        model.setRowCount(0);
        for (Film f : fs.findAll()) {
            model.addRow(new Object[]{
                f.getId(),
                f.getTitre(),
                f.getGenre(),
                f.getDuree(),
                f.getRealisateur()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        titretxt = new javax.swing.JTextField();
        genretxt = new javax.swing.JTextField();
        dureetxt = new javax.swing.JTextField();
        realisateurtxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAjouter = new javax.swing.JButton();
        deleteBn = new javax.swing.JButton();
        updateBn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeFilms = new javax.swing.JTable();
        logoLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(10, 10, 10));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Titre :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Genre :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Duree :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 25));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 205, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Realisateur :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 25));

        titretxt.setBackground(new java.awt.Color(20, 20, 20));
        titretxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titretxt.setForeground(new java.awt.Color(255, 255, 255));
        titretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titretxtActionPerformed(evt);
            }
        });
        jPanel1.add(titretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 35, 320, 35));

        genretxt.setBackground(new java.awt.Color(20, 20, 20));
        genretxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genretxt.setForeground(new java.awt.Color(255, 255, 255));
        genretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genretxtActionPerformed(evt);
            }
        });
        jPanel1.add(genretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 85, 320, 35));

        dureetxt.setBackground(new java.awt.Color(20, 20, 20));
        dureetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dureetxt.setForeground(new java.awt.Color(255, 255, 255));
        dureetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dureetxtActionPerformed(evt);
            }
        });
        jPanel1.add(dureetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 135, 320, 35));

        realisateurtxt.setBackground(new java.awt.Color(20, 20, 20));
        realisateurtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        realisateurtxt.setForeground(new java.awt.Color(255, 255, 255));
        realisateurtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realisateurtxtActionPerformed(evt);
            }
        });
        jPanel1.add(realisateurtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 185, 320, 35));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 18, -1, 351));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 10, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 530, 260));

        jPanel3.setBackground(new java.awt.Color(10, 10, 10));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAjouter.setBackground(new java.awt.Color(229, 57, 53));
        btnAjouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAjouter.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouter.setText("Ajouter");
        btnAjouter.setBorderPainted(false);
        btnAjouter.setFocusPainted(false);
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        jPanel3.add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 120, 40));

        deleteBn.setBackground(new java.awt.Color(180, 40, 40));
        deleteBn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBn.setText("Supprimer");
        deleteBn.setBorderPainted(false);
        deleteBn.setFocusPainted(false);
        deleteBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBnActionPerformed(evt);
            }
        });
        jPanel3.add(deleteBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 40));

        updateBn.setBackground(new java.awt.Color(30, 144, 255));
        updateBn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBn.setForeground(new java.awt.Color(255, 255, 255));
        updateBn.setText("Modifier");
        updateBn.setBorderPainted(false);
        updateBn.setFocusPainted(false);
        updateBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBnActionPerformed(evt);
            }
        });
        jPanel3.add(updateBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 200, 260));

        jPanel4.setBackground(new java.awt.Color(10, 10, 10));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listeFilms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Titre", "Genre", "Duree", "Realisateur"
            }
        ));
        listeFilms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeFilmsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeFilms);
        if (listeFilms.getColumnModel().getColumnCount() > 0) {
            listeFilms.getColumnModel().getColumn(0).setHeaderValue("id");
            listeFilms.getColumnModel().getColumn(1).setHeaderValue("Titre");
            listeFilms.getColumnModel().getColumn(2).setHeaderValue("Genre");
            listeFilms.getColumnModel().getColumn(3).setHeaderValue("Duree");
            listeFilms.getColumnModel().getColumn(4).setHeaderValue("Realisateur");
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 750, 300));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 740, 320));

        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Original Computer\\Desktop\\log1.png")); // NOI18N
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 140, 120));

        jPanel6.setBackground(new java.awt.Color(10, 10, 10));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Information du Film");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 400, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        fs.create(new Film(titretxt.getText(), genretxt.getText(), Integer.parseInt(dureetxt.getText()), realisateurtxt.getText()));
        vider();

        load();
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void deleteBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBnActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous supprimer ce film ?");
        if (reponse == 0) {
            fs.delete(fs.findById(id));
            load();
            vider();
        }
    }//GEN-LAST:event_deleteBnActionPerformed

    private void listeFilmsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeFilmsMouseClicked
        // TODO add your handling code here:
        id = Integer.parseInt(model.getValueAt(listeFilms.getSelectedRow(), 0).toString());
        //JOptionPane.showMessageDialog(this, "id = "+id);
        titretxt.setText(model.getValueAt(listeFilms.getSelectedRow(), 1).toString());
        genretxt.setText(model.getValueAt(listeFilms.getSelectedRow(), 2).toString());
        dureetxt.setText(model.getValueAt(listeFilms.getSelectedRow(), 3).toString());
        realisateurtxt.setText(model.getValueAt(listeFilms.getSelectedRow(), 4).toString());


    }//GEN-LAST:event_listeFilmsMouseClicked

    private void updateBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBnActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous modifier ce film ?");
        if (reponse == 0) {
            fs.update(new Film(id, titretxt.getText().toString(), genretxt.getText().toString(), Integer.parseInt(dureetxt.getText().toString()), realisateurtxt.getText().toString()));
            load();
            vider();
        }
    }//GEN-LAST:event_updateBnActionPerformed

    private void realisateurtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realisateurtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realisateurtxtActionPerformed

    private void dureetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dureetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dureetxtActionPerformed

    private void genretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genretxtActionPerformed

    private void titretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titretxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton deleteBn;
    private javax.swing.JTextField dureetxt;
    private javax.swing.JTextField genretxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeFilms;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField realisateurtxt;
    private javax.swing.JTextField titretxt;
    private javax.swing.JButton updateBn;
    // End of variables declaration//GEN-END:variables

    private void vider() {
        titretxt.setText("");
        genretxt.setText("");
        dureetxt.setText("");
        realisateurtxt.setText("");
    }

    private void applyFilmTheme() {
        java.awt.Color bg = new java.awt.Color(10, 10, 10);
        java.awt.Color fieldBg = new java.awt.Color(20, 20, 20);
        java.awt.Color border = new java.awt.Color(60, 60, 60);

        // panels fond sombre
        jPanel1.setBackground(bg);
        jPanel3.setBackground(bg);
        jPanel4.setBackground(bg);

        // labels blancs
        jLabel1.setForeground(java.awt.Color.WHITE);
        jLabel2.setForeground(java.awt.Color.WHITE);
        jLabel3.setForeground(java.awt.Color.WHITE);
        jLabel5.setForeground(java.awt.Color.WHITE);

        // champs sombres
        javax.swing.JTextField[] fields = {titretxt, genretxt, dureetxt, realisateurtxt};
        for (javax.swing.JTextField tf : fields) {
            tf.setBackground(fieldBg);
            tf.setForeground(java.awt.Color.WHITE);
            tf.setCaretColor(java.awt.Color.WHITE);
            tf.setBorder(javax.swing.BorderFactory.createLineBorder(border, 1, true));
        }

        // tableau sombre
        listeFilms.setBackground(fieldBg);
        listeFilms.setForeground(java.awt.Color.WHITE);
        listeFilms.setSelectionBackground(new java.awt.Color(60, 60, 60));
        listeFilms.setGridColor(border);
        listeFilms.getTableHeader().setBackground(new java.awt.Color(25, 25, 25));
        listeFilms.getTableHeader().setForeground(java.awt.Color.WHITE);

        listeFilms.getTableHeader().setOpaque(false);
        listeFilms.getTableHeader().setBackground(new java.awt.Color(15, 15, 15));
        listeFilms.getTableHeader().setForeground(java.awt.Color.WHITE);
        listeFilms.getTableHeader().setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 13));

    }

    private void addHoverEffect() {

        // hover Ajouter
        btnAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAjouter.setBackground(new java.awt.Color(200, 40, 40));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAjouter.setBackground(new java.awt.Color(229, 57, 53));
            }
        });

        // hover Supprimer
        deleteBn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBn.setBackground(new java.awt.Color(150, 30, 30));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBn.setBackground(new java.awt.Color(180, 40, 40));
            }
        });

        // hover Modifier
        updateBn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBn.setBackground(new java.awt.Color(20, 120, 220));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBn.setBackground(new java.awt.Color(30, 144, 255));
            }
        });
    }

}
