/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ul;

import connexion.Connexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Original Computer
 */
public class FiltrageSeanceForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form FiltrageSeanceForm
     */
    public FiltrageSeanceForm() {
        initComponents();
        setTitle("Filtrage des séances par genre / date");
        loadGenres();
        loadAllSeances();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelFiltre = new javax.swing.JPanel();
        lblGenre = new javax.swing.JLabel();
        cmbGenre = new javax.swing.JComboBox();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnFiltrer = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeances = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 20, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, -1, -1));

        panelFiltre.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrage des séances"));
        panelFiltre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGenre.setText("Genre :");
        panelFiltre.add(lblGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 68, -1, -1));

        cmbGenre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenreActionPerformed(evt);
            }
        });
        panelFiltre.add(cmbGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 65, 165, -1));

        lblDate.setText("Date : ");
        panelFiltre.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 134, -1, -1));
        panelFiltre.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 134, 165, -1));

        btnFiltrer.setText("Filtrer");
        btnFiltrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrerActionPerformed(evt);
            }
        });
        panelFiltre.add(btnFiltrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 100, -1));

        btnReset.setText("Réinitialiser");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        panelFiltre.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        panelTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSeances.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Film", "Genre", "Salle", "Date projection ", "Prix", "Tickets Vendus"
            }
        ));
        jScrollPane1.setViewportView(tblSeances);

        panelTable.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 690, 230));

        panelFiltre.add(panelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 710, 280));

        getContentPane().add(panelFiltre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenreActionPerformed

    private void btnFiltrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrerActionPerformed
        // TODO add your handling code here:
        String genre = cmbGenre.getSelectedItem().toString();
        String dateTxt = txtDate.getText().trim();

        java.util.Date d = null;

        // si l'utilisateur a tapé une date
        if (!dateTxt.isEmpty()) {
            try {
                // format obligatoire : yyyy-mm-dd
                d = java.sql.Date.valueOf(dateTxt);
            } catch (IllegalArgumentException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Format date invalide !\nUtilise : yyyy-mm-dd",
                        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
                return; // stop si date fausse
            }
        }

        loadSeancesFiltered(genre, d);

    }//GEN-LAST:event_btnFiltrerActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cmbGenre.setSelectedIndex(0); // remet "Tous"
        txtDate.setText("");          // vide la date
        loadAllSeances();             // recharge toutes les séances
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrer;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cmbGenre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JPanel panelFiltre;
    private javax.swing.JPanel panelTable;
    private javax.swing.JTable tblSeances;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables

    private void loadGenres() {
        try {
            cmbGenre.removeAllItems();
            cmbGenre.addItem("Tous");

            String sql = "SELECT DISTINCT genre FROM Film ORDER BY genre";
            PreparedStatement ps = Connexion.getConnection().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                cmbGenre.addItem(rs.getString("genre"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void loadAllSeances() {
        loadSeancesFiltered("Tous", null);
    }

    private void loadSeancesFiltered(String genre, java.util.Date date) {
        DefaultTableModel model = (DefaultTableModel) tblSeances.getModel();
        model.setRowCount(0);

        StringBuilder sql = new StringBuilder();
        sql.append("SELECT f.titre, f.genre, sa.nom AS salle, ")
                .append("s.dateProjection, s.prix, s.ticketsVendus ")
                .append("FROM Seance s ")
                .append("JOIN Film f ON s.film_id = f.id ")
                .append("JOIN Salle sa ON s.salle_id = sa.id ")
                .append("WHERE 1=1 ");

        if (!"Tous".equals(genre)) {
            sql.append("AND f.genre = ? ");
        }

        if (date != null) {
            sql.append("AND DATE(s.dateProjection) = ? ");
        }

        sql.append("ORDER BY s.dateProjection");

        try {
            PreparedStatement ps = Connexion.getConnection().prepareStatement(sql.toString());

            int i = 1;
            if (!"Tous".equals(genre)) {
                ps.setString(i++, genre);
            }

            if (date != null) {
                ps.setDate(i++, new java.sql.Date(date.getTime()));
            }

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] row = {
                    rs.getString("titre"),
                    rs.getString("genre"),
                    rs.getString("salle"),
                    rs.getTimestamp("dateProjection"),
                    rs.getDouble("prix"),
                    rs.getInt("ticketsVendus")
                };
                model.addRow(row);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
