/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ul;

import javax.swing.JOptionPane;
import services.UtilisateurService;

/**
 *
 * @author Original Computer
 */
public class ForgotPasswordDialog extends javax.swing.JDialog {

    private UtilisateurService utilisateurService = new UtilisateurService();

    /**
     * Creates new form ForgotPasswordDialog
     */
    public ForgotPasswordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, true);
        initComponents();
        this.setTitle("Recupere mots de passe - Gestion Cinéma");
        setLocationRelativeTo(parent);

        
        //Hover bouton récup
        recoverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recoverBtn.setBackground(new java.awt.Color(200, 40, 40));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                recoverBtn.setBackground(new java.awt.Color(229, 57, 53));
            }
        });

        // taille fixe (style login)
        setSize(600, 500);
        setResizable(false);

        // fond sombre
        jPanel1.setBackground(new java.awt.Color(10, 10, 10));

        // titre blanc
        jLabel1.setForeground(java.awt.Color.WHITE);
        jLabel2.setForeground(java.awt.Color.WHITE);

        // champ sombre
        emailtxt.setBackground(new java.awt.Color(20, 20, 20));
        emailtxt.setForeground(java.awt.Color.WHITE);
        emailtxt.setCaretColor(java.awt.Color.WHITE);
        emailtxt.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(120, 120, 120), 1, true));

        // bouton rouge sans bord focus
        recoverBtn.setBackground(new java.awt.Color(229, 57, 53));
        recoverBtn.setForeground(java.awt.Color.WHITE);
        recoverBtn.setFocusPainted(false);
        recoverBtn.setBorderPainted(false);
        
        //Placeholder email
        emailtxt.setText("Email");
        emailtxt.setForeground(new java.awt.Color(160, 160, 160));

        emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (emailtxt.getText().equals("Email")) {
                    emailtxt.setText("");
                    emailtxt.setForeground(java.awt.Color.WHITE);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (emailtxt.getText().isEmpty()) {
                    emailtxt.setText("Email");
                    emailtxt.setForeground(new java.awt.Color(160, 160, 160));
                }
            }
        });


    }

    /**
     * ForgotPasswordDialog(LoginForm aThis) { throw new
     * UnsupportedOperationException("Not supported yet."); //To change body of
     * generated methods, choose Tools | Templates. }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        recoverBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Récupération mot de passe");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 350, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(200, 200, 200));
        jLabel2.setText("Votre Email :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, 25));

        emailtxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel1.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 360, 45));

        recoverBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        recoverBtn.setForeground(new java.awt.Color(255, 255, 255));
        recoverBtn.setText("Recuperer");
        recoverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(recoverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 360, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Original Computer\\Desktop\\log1.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 140, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void recoverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoverBtnActionPerformed
        // TODO add your handling code here:
        String email = emailtxt.getText().trim();

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer votre email !");
            return;
        }

        boolean ok = utilisateurService.recoverAndSendNewPassword(email);

        if (ok) {
            JOptionPane.showMessageDialog(this,
                    "Un nouveau mot de passe a été envoyé à votre email.");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Email non trouvé ou erreur d’envoi !");
        }

    }//GEN-LAST:event_recoverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ForgotPasswordDialog dialog = new ForgotPasswordDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton recoverBtn;
    // End of variables declaration//GEN-END:variables
}
