/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ul;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Original Computer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {

        initComponents();

        this.setTitle("Gestion de cinema");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        filmMenu = new javax.swing.JMenuItem();
        salleMenu = new javax.swing.JMenuItem();
        seanceMenu = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        filtrageMenuItem = new javax.swing.JMenuItem();
        graphRecettesMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cinema");

        filmMenu.setMnemonic('o');
        filmMenu.setText("Film");
        filmMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmMenuActionPerformed(evt);
            }
        });
        fileMenu.add(filmMenu);

        salleMenu.setMnemonic('s');
        salleMenu.setText("Salle");
        salleMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salleMenuActionPerformed(evt);
            }
        });
        fileMenu.add(salleMenu);

        seanceMenu.setMnemonic('a');
        seanceMenu.setText("Seance");
        seanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seanceMenuActionPerformed(evt);
            }
        });
        fileMenu.add(seanceMenu);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Fonctionnalite");

        filtrageMenuItem.setMnemonic('t');
        filtrageMenuItem.setText("Filtrage");
        filtrageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrageMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(filtrageMenuItem);

        graphRecettesMenuItem.setMnemonic('y');
        graphRecettesMenuItem.setText("Graphique Recettes");
        graphRecettesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphRecettesMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(graphRecettesMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void salleMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salleMenuActionPerformed
        // TODO add your handling code here:
        SalleForm sf = new SalleForm();
        desktopPane.add(sf);
        sf.setVisible(true);
    }//GEN-LAST:event_salleMenuActionPerformed

    private void filmMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmMenuActionPerformed
        // TODO add your handling code here:
        FilmForm ff = new FilmForm();
        desktopPane.add(ff);
        ff.setVisible(true);

    }//GEN-LAST:event_filmMenuActionPerformed

    private void seanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seanceMenuActionPerformed
        // TODO add your handling code here:
        SeanceForm sef = new SeanceForm();
        desktopPane.add(sef);
        sef.setVisible(true);
    }//GEN-LAST:event_seanceMenuActionPerformed

    private void filtrageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrageMenuItemActionPerformed
        // TODO add your handling code here:
        FiltrageSeanceForm f = new FiltrageSeanceForm();
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_filtrageMenuItemActionPerformed

    private void graphRecettesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphRecettesMenuItemActionPerformed
        // TODO add your handling code here:
        RecettesChartForm f = new RecettesChartForm();
        desktopPane.add(f);   
        f.setVisible(true);
    }//GEN-LAST:event_graphRecettesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem filmMenu;
    private javax.swing.JMenuItem filtrageMenuItem;
    private javax.swing.JMenuItem graphRecettesMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem salleMenu;
    private javax.swing.JMenuItem seanceMenu;
    // End of variables declaration//GEN-END:variables

}
