/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ul;

import connexion.Connexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Original Computer
 */
public class RecettesChartForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form RecettesChartForm
     */
    public RecettesChartForm() {
        initComponents();
        updateChartRecettesParMois("2025");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChart = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pnlChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlChart;
    // End of variables declaration//GEN-END:variables

    private void updateChartRecettesParMois(String annee) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        try {
            String sql
                    = "SELECT MONTH(dateProjection) AS mois, "
                    + "       SUM(prix * ticketsVendus) AS recette "
                    + "FROM Seance "
                    + "WHERE YEAR(dateProjection) = ? "
                    + "GROUP BY MONTH(dateProjection) "
                    + "ORDER BY mois";

            PreparedStatement ps = Connexion.getConnection().prepareStatement(sql);
            ps.setString(1, annee);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int mois = rs.getInt("mois");
                double recette = rs.getDouble("recette");

                String labelMois = String.format("%02d", mois); // 01..12
                dataset.addValue(recette, "Recettes", labelMois);
            }

            JFreeChart chart = ChartFactory.createBarChart(
                    "Recettes par mois - " + annee,
                    "Mois",
                    "Recettes (DH)",
                    dataset,
                    PlotOrientation.VERTICAL,
                    true, true, false
            );

            chart.setBackgroundPaint(Color.WHITE);
            CategoryPlot plot = chart.getCategoryPlot();
            plot.setBackgroundPaint(Color.WHITE);
            plot.setRangeGridlinePaint(Color.GRAY);
            BarRenderer renderer = (BarRenderer) plot.getRenderer();
            renderer.setSeriesPaint(0, new Color(0, 102, 204)); // bleu

            ChartPanel chartPanel = new ChartPanel(chart);

            pnlChart.removeAll();
            pnlChart.setLayout(new BorderLayout());
            pnlChart.add(chartPanel, BorderLayout.CENTER);
            pnlChart.revalidate();
            pnlChart.repaint();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
