/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ul;

import javax.swing.JOptionPane;
import model.Utilisateur;
import services.UtilisateurService;

/**
 *
 * @author Original Computer
 */
public class RegisterForm extends javax.swing.JFrame {

    UtilisateurService utilisateurService = new UtilisateurService();

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setTitle("Créer un compte");
        setSize(600, 520);
        setResizable(false);

        

        // champs sombres
        txtemail.setBackground(new java.awt.Color(20, 20, 20));
        txtemail.setForeground(java.awt.Color.WHITE);
        txtemail.setCaretColor(java.awt.Color.WHITE);
        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(120, 120, 120), 1, true));

        txtpassword.setBackground(new java.awt.Color(20, 20, 20));
        txtpassword.setForeground(java.awt.Color.WHITE);
        txtpassword.setCaretColor(java.awt.Color.WHITE);
        txtpassword.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(120, 120, 120), 1, true));

        // bouton rouge
        registerBn.setBackground(new java.awt.Color(229, 57, 53));
        registerBn.setForeground(java.awt.Color.WHITE);
        registerBn.setFocusPainted(false);
        registerBn.setBorderPainted(false);

        // placeholder Email
        txtemail.setText("Email");
        txtemail.setForeground(new java.awt.Color(160, 160, 160));
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtemail.getText().equals("Email")) {
                    txtemail.setText("");
                    txtemail.setForeground(java.awt.Color.WHITE);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtemail.getText().isEmpty()) {
                    txtemail.setText("Email");
                    txtemail.setForeground(new java.awt.Color(160, 160, 160));
                }
            }
        });

        // placeholder Password
        txtpassword.setText("Mot de passe");
        txtpassword.setEchoChar((char) 0);
        txtpassword.setForeground(new java.awt.Color(160, 160, 160));
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                String pass = new String(txtpassword.getPassword());
                if (pass.equals("Mot de passe")) {
                    txtpassword.setText("");
                    txtpassword.setEchoChar('•');
                    txtpassword.setForeground(java.awt.Color.WHITE);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                String pass = new String(txtpassword.getPassword());
                if (pass.isEmpty()) {
                    txtpassword.setText("Mot de passe");
                    txtpassword.setEchoChar((char) 0);
                    txtpassword.setForeground(new java.awt.Color(160, 160, 160));
                }
            }
        });

        //Hover sur bouton
        registerBn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerBn.setBackground(new java.awt.Color(200, 40, 40));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerBn.setBackground(new java.awt.Color(229, 57, 53));
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        registerBn = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 109, 106, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Créer un compte");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(200, 200, 200));
        jLabel6.setText("Email :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 101, -1));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 360, 45));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 229, 53, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(200, 200, 200));
        jLabel8.setText("Mot de passe :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 101, -1));

        registerBn.setBackground(new java.awt.Color(229, 57, 53));
        registerBn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        registerBn.setForeground(new java.awt.Color(255, 255, 255));
        registerBn.setText("Créer");
        registerBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 360, 50));

        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 360, 45));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Original Computer\\Desktop\\log1.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 140, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void registerBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBnActionPerformed
        // TODO add your handling code here:
        String email = txtemail.getText();
        String password = new String(txtpassword.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires !");
            return;
        }

        Utilisateur u = new Utilisateur(email, password);

        if (utilisateurService.register(u)) {
            JOptionPane.showMessageDialog(this, "Compte créé avec succès !");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Email déjà utilisé !");
        }

    }//GEN-LAST:event_registerBnActionPerformed

    private javax.swing.JLabel jLabel1, jLabel2, jLabel3;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerBn;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables

}
