/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ul;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Salle;
import services.SalleService;

/**
 *
 * @author Original Computer
 */
public class SalleForm extends javax.swing.JInternalFrame {

    SalleService ss = null;
    DefaultTableModel model = null;
    static int id;

    /**
     * Creates new form SalleForm
     */
    public SalleForm() {
        initComponents();
        this.setTitle("Gestion des salles");

        applySalleTheme();
        addHoverEffect();

        ss = new SalleService();
        model = (DefaultTableModel) listeSalles.getModel();
        load();
    }

    public void load() {
        model.setRowCount(0);
        for (Salle s : ss.findAll()) {
            model.addRow(new Object[]{
                s.getId(),
                s.getNom(),
                s.getCapacite()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomtxt = new javax.swing.JTextField();
        capacitetxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ajouterBn = new javax.swing.JButton();
        updateBn = new javax.swing.JButton();
        deleteBn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeSalles = new javax.swing.JTable();
        logoLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setBackground(new java.awt.Color(10, 10, 10));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Capacité :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 25));

        nomtxt.setBackground(new java.awt.Color(25, 25, 25));
        nomtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomtxt.setForeground(new java.awt.Color(255, 255, 255));
        nomtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 70, 70)));
        nomtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomtxtActionPerformed(evt);
            }
        });
        jPanel1.add(nomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 55, 300, 30));

        capacitetxt.setBackground(new java.awt.Color(25, 25, 25));
        capacitetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        capacitetxt.setForeground(new java.awt.Color(255, 255, 255));
        capacitetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 70, 70)));
        jPanel1.add(capacitetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 115, 300, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 520, 220));

        jPanel2.setBackground(new java.awt.Color(15, 15, 15));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ajouterBn.setBackground(new java.awt.Color(255, 80, 80));
        ajouterBn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ajouterBn.setForeground(new java.awt.Color(255, 255, 255));
        ajouterBn.setText("Ajouter");
        ajouterBn.setBorderPainted(false);
        ajouterBn.setFocusPainted(false);
        ajouterBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBnActionPerformed(evt);
            }
        });
        jPanel2.add(ajouterBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 35));

        updateBn.setBackground(new java.awt.Color(50, 140, 255));
        updateBn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBn.setForeground(new java.awt.Color(255, 255, 255));
        updateBn.setText("Modifier");
        updateBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBnActionPerformed(evt);
            }
        });
        jPanel2.add(updateBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 35));

        deleteBn.setBackground(new java.awt.Color(220, 60, 60));
        deleteBn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBn.setText("Supprimer");
        deleteBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 95, 120, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 200, 220));

        jPanel3.setBackground(new java.awt.Color(15, 15, 15));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listeSalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Capacite"
            }
        ));
        listeSalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeSallesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listeSalles);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 240));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 740, 250));

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Original Computer\\Desktop\\log1.png")); // NOI18N
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 170, 130));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Gestion des salles");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 270, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBnActionPerformed
        // TODO add your handling code here:
        ss.create(new Salle(nomtxt.getText(), Integer.parseInt(capacitetxt.getText())));
        vider();
        load();
    }//GEN-LAST:event_ajouterBnActionPerformed

    private void deleteBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous supprimer ce film ?");
        if (reponse == 0) {
            ss.delete(ss.findById(id));
            load();
            vider();
        }
    }//GEN-LAST:event_deleteBnActionPerformed

    private void updateBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBnActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous modifier ce film ?");
        if (reponse == 0) {
            ss.update(new Salle(id, nomtxt.getText().toString(), Integer.parseInt(capacitetxt.getText().toString())));
            load();
            vider();
        }
    }//GEN-LAST:event_updateBnActionPerformed

    private void listeSallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeSallesMouseClicked
        // TODO add your handling code here:
        id = Integer.parseInt(model.getValueAt(listeSalles.getSelectedRow(), 0).toString());
        //JOptionPane.showMessageDialog(this, "id = "+id);
        nomtxt.setText(model.getValueAt(listeSalles.getSelectedRow(), 1).toString());
        capacitetxt.setText(model.getValueAt(listeSalles.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_listeSallesMouseClicked

    private void nomtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomtxtActionPerformed

    private void vider() {
        nomtxt.setText("");
        capacitetxt.setText("");

    }

    private void applySalleTheme() {
        getContentPane().setBackground(new java.awt.Color(10, 10, 10));

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel2.setBackground(new java.awt.Color(15, 15, 15));
        jPanel3.setBackground(new java.awt.Color(15, 15, 15));

        nomtxt.setBackground(new java.awt.Color(25, 25, 25));
        nomtxt.setForeground(java.awt.Color.WHITE);

        capacitetxt.setBackground(new java.awt.Color(25, 25, 25));
        capacitetxt.setForeground(java.awt.Color.WHITE);

        listeSalles.setBackground(new java.awt.Color(10, 10, 10));
        listeSalles.setForeground(java.awt.Color.WHITE);
        listeSalles.setRowHeight(24);
    }

    private void addHoverEffect() {
        addHover(ajouterBn, new java.awt.Color(255, 80, 80), new java.awt.Color(255, 120, 120));
        addHover(deleteBn, new java.awt.Color(220, 60, 60), new java.awt.Color(255, 90, 90));
        addHover(updateBn, new java.awt.Color(50, 140, 255), new java.awt.Color(90, 170, 255));
    }

    private void addHover(javax.swing.JButton btn, java.awt.Color normal, java.awt.Color hover) {
        btn.setBackground(normal);
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(hover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(normal);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterBn;
    private javax.swing.JTextField capacitetxt;
    private javax.swing.JButton deleteBn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable listeSalles;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateBn;
    // End of variables declaration//GEN-END:variables
}
