/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ul;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.Film;
import model.Salle;
import model.Seance;
import services.FilmService;
import services.SalleService;
import services.SeanceService;

/**
 *
 * @author Original Computer
 */
public class SeanceForm extends javax.swing.JInternalFrame {

    SeanceService seanceService = null;
    FilmService filmService = null;
    SalleService salleService = null;
    DefaultTableModel model = null;
    static int id;

    /**
     * Creates new form SeanceForm
     */
    public SeanceForm() {
        initComponents();
        this.setTitle("Gestion des séances");
        seanceService = new SeanceService();
        filmService = new FilmService();
        salleService = new SalleService();
        model = (DefaultTableModel) listeSeances.getModel();
        setupDateTimeSpinner();
        loadData();
        load();
        addHoverEffect();
        

    }

    private void setupDateTimeSpinner() {
        // Créer un modèle de date pour le spinner
        SpinnerDateModel dateModel = new SpinnerDateModel();
        setupDateTime.setModel(dateModel);

        // Configurer l'éditeur pour afficher date ET heure
        javax.swing.JSpinner.DateEditor dateEditor = new javax.swing.JSpinner.DateEditor(
                setupDateTime,
                "dd/MM/yyyy HH:mm" // Format : date + heure
        );
        setupDateTime.setEditor(dateEditor);

        // Définir la date/heure actuelle par défaut
        setupDateTime.setValue(new java.util.Date());
    }

    public void load() {
        model.setRowCount(0);
        SimpleDateFormat sdfDate = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat sdfHeure = new SimpleDateFormat("HH:mm");

        for (Seance s : seanceService.findAll()) {
            java.util.Date date = java.util.Date.from(
                    s.getDateProjection().atZone(ZoneId.systemDefault()).toInstant()
            );

            model.addRow(new Object[]{
                s.getId(),
                s.getFilm().getTitre(),
                s.getSalle().getNom(),
                sdfDate.format(date),
                sdfHeure.format(date),
                String.format("%.2f", s.getPrix()),
                s.getTicketsVendus()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localeStrings1 = new de.wannawork.jcalendar.LocaleStrings();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        filmtxt = new javax.swing.JLabel();
        salletxt = new javax.swing.JLabel();
        dateProjectiontxt = new javax.swing.JLabel();
        prix = new javax.swing.JLabel();
        jpnel2 = new javax.swing.JLabel();
        comboFilm = new javax.swing.JComboBox();
        comboSalle = new javax.swing.JComboBox();
        setupDateTime = new javax.swing.JSpinner();
        prixtxt = new javax.swing.JTextField();
        ticketsvendustxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ajouterBn = new javax.swing.JButton();
        updateBn = new javax.swing.JButton();
        deleteBn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeSeances = new javax.swing.JTable();

        setBackground(new java.awt.Color(10, 10, 10));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des seances");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(10, 10, 10));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filmtxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        filmtxt.setForeground(new java.awt.Color(255, 255, 255));
        filmtxt.setText("Film :");
        jPanel1.add(filmtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 25));

        salletxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        salletxt.setForeground(new java.awt.Color(255, 255, 255));
        salletxt.setText("Salle :");
        jPanel1.add(salletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 85, 80, 35));

        dateProjectiontxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dateProjectiontxt.setForeground(new java.awt.Color(255, 255, 255));
        dateProjectiontxt.setText("Date de projection :");
        jPanel1.add(dateProjectiontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 140, 25));

        prix.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        prix.setForeground(new java.awt.Color(255, 255, 255));
        prix.setText("Prix :");
        jPanel1.add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 175, 120, 25));

        jpnel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jpnel2.setForeground(new java.awt.Color(255, 255, 255));
        jpnel2.setText("Tickets vendus :");
        jPanel1.add(jpnel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 140, 25));

        comboFilm.setBackground(new java.awt.Color(25, 25, 25));
        comboFilm.setForeground(new java.awt.Color(255, 255, 255));
        comboFilm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilmActionPerformed(evt);
            }
        });
        jPanel1.add(comboFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 35, 320, 35));

        comboSalle.setBackground(new java.awt.Color(25, 25, 25));
        comboSalle.setForeground(new java.awt.Color(255, 255, 255));
        comboSalle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSalleActionPerformed(evt);
            }
        });
        jPanel1.add(comboSalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 320, 35));

        setupDateTime.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(setupDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 125, 320, 35));

        prixtxt.setBackground(new java.awt.Color(25, 25, 25));
        prixtxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        prixtxt.setForeground(new java.awt.Color(255, 255, 255));
        prixtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixtxtActionPerformed(evt);
            }
        });
        jPanel1.add(prixtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 320, 35));

        ticketsvendustxt.setBackground(new java.awt.Color(25, 25, 25));
        ticketsvendustxt.setForeground(new java.awt.Color(255, 255, 255));
        ticketsvendustxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketsvendustxtActionPerformed(evt);
            }
        });
        jPanel1.add(ticketsvendustxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 215, 320, 35));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 600, 260));

        jPanel2.setBackground(new java.awt.Color(15, 15, 15));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ajouterBn.setBackground(new java.awt.Color(229, 57, 53));
        ajouterBn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ajouterBn.setForeground(new java.awt.Color(255, 255, 255));
        ajouterBn.setText("Ajouter");
        ajouterBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBnActionPerformed(evt);
            }
        });
        jPanel2.add(ajouterBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 40));

        updateBn.setBackground(new java.awt.Color(30, 144, 255));
        updateBn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBn.setForeground(new java.awt.Color(255, 255, 255));
        updateBn.setText("Modifier");
        updateBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBnActionPerformed(evt);
            }
        });
        jPanel2.add(updateBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, 40));

        deleteBn.setBackground(new java.awt.Color(180, 40, 40));
        deleteBn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBn.setText("Supprimer");
        deleteBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 40));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 200, 250));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Original Computer\\Desktop\\log1.png")); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 180, 120));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Gestion des séances");
        jPanel4.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 900, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 470));

        jPanel3.setBackground(new java.awt.Color(15, 15, 15));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listeSeances.setBackground(new java.awt.Color(20, 20, 20));
        listeSeances.setForeground(new java.awt.Color(255, 255, 255));
        listeSeances.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Film", "Salle", "Date de projection", "heure", "Prix", "Tickets vendus"
            }
        ));
        listeSeances.setGridColor(new java.awt.Color(70, 70, 70));
        listeSeances.setRowHeight(24);
        listeSeances.setSelectionBackground(new java.awt.Color(102, 102, 102));
        listeSeances.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeSeancesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeSeances);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 240));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 830, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBnActionPerformed
        // TODO add your handling code here:
        try {
            // Validation
            if (comboFilm.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner un film !");
                return;
            }

            if (comboSalle.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une salle !");
                return;
            }

            if (prixtxt.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Veuillez entrer le prix !");
                return;
            }

            Film film = (Film) comboFilm.getSelectedItem();
            Salle salle = (Salle) comboSalle.getSelectedItem();

            java.util.Date dateUtil = (java.util.Date) setupDateTime.getValue();
            LocalDateTime dateProjection = dateUtil.toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDateTime();

            double prix = Double.parseDouble(prixtxt.getText());
            int tickets = jpnel2.getText().isEmpty() ? 0 : Integer.parseInt(ticketsvendustxt.getText());

            if (tickets > salle.getCapacite()) {
                JOptionPane.showMessageDialog(this, "Capacité dépassée ! Maximum: " + salle.getCapacite());
                return;
            }

            Seance seance = new Seance(film, salle, dateProjection, prix, tickets);
            seanceService.create(seance);

            vider();
            load();

            JOptionPane.showMessageDialog(this, "Séance ajoutée avec succès !");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Prix ou tickets invalide !");
        }
    }//GEN-LAST:event_ajouterBnActionPerformed

    private void updateBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBnActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous modifier cette séance ?");
        if (reponse == 0) {
            try {
                Film film = (Film) comboFilm.getSelectedItem();
                Salle salle = (Salle) comboSalle.getSelectedItem();

                java.util.Date dateUtil = (java.util.Date) setupDateTime.getValue();
                LocalDateTime dateProjection = dateUtil.toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDateTime();

                double prix = Double.parseDouble(prixtxt.getText());
                int tickets = Integer.parseInt(ticketsvendustxt.getText());

                Seance seance = new Seance(film, salle, dateProjection, prix, tickets);
                seance.setId(id);

                seanceService.update(seance);
                load();
                vider();

                JOptionPane.showMessageDialog(this, "Séance modifiée !");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erreur: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_updateBnActionPerformed

    private void deleteBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBnActionPerformed
        // TODO add your handling code here
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous supprimer cette séance ?");
        if (reponse == 0) {
            seanceService.delete(seanceService.findById(id));
            load();
            vider();
            JOptionPane.showMessageDialog(this, "Séance supprimée !");
        }
    }//GEN-LAST:event_deleteBnActionPerformed

    private void listeSeancesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeSeancesMouseClicked
        // TODO add your handling code here:
        try {
            id = Integer.parseInt(model.getValueAt(listeSeances.getSelectedRow(), 0).toString());

            Seance seance = seanceService.findById(id);

            if (seance != null) {
                // Sélectionner le film
                for (int i = 0; i < comboFilm.getItemCount(); i++) {
                    Film f = (Film) comboFilm.getItemAt(i);
                    if (f.getId() == seance.getFilm().getId()) {
                        comboFilm.setSelectedIndex(i);
                        break;
                    }
                }

                // Sélectionner la salle
                for (int i = 0; i < comboSalle.getItemCount(); i++) {
                    Salle s = (Salle) comboSalle.getItemAt(i);
                    if (s.getId() == seance.getSalle().getId()) {
                        comboSalle.setSelectedIndex(i);
                        break;
                    }
                }

                // Définir la date/heure
                java.util.Date date = java.util.Date.from(
                        seance.getDateProjection().atZone(ZoneId.systemDefault()).toInstant()
                );
                setupDateTime.setValue(date);

                prixtxt.setText(String.valueOf(seance.getPrix()));
                ticketsvendustxt.setText(String.valueOf(seance.getTicketsVendus()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_listeSeancesMouseClicked

    private void comboSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSalleActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboSalleActionPerformed

    private void comboFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilmActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboFilmActionPerformed

    private void ticketsvendustxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketsvendustxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketsvendustxtActionPerformed

    private void prixtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixtxtActionPerformed

    private void addHoverEffect() {
        addHover(ajouterBn, new java.awt.Color(229, 57, 53), new java.awt.Color(200, 40, 40));
        addHover(deleteBn, new java.awt.Color(180, 40, 40), new java.awt.Color(150, 30, 30));
        addHover(updateBn, new java.awt.Color(30, 144, 255), new java.awt.Color(20, 110, 210));
    }

    private void addHover(javax.swing.JButton btn, java.awt.Color normal, java.awt.Color hover) {
        btn.setBackground(normal);
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(hover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(normal);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterBn;
    private javax.swing.JComboBox comboFilm;
    private javax.swing.JComboBox comboSalle;
    private javax.swing.JLabel dateProjectiontxt;
    private javax.swing.JButton deleteBn;
    private javax.swing.JLabel filmtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jpnel2;
    private javax.swing.JTable listeSeances;
    private de.wannawork.jcalendar.LocaleStrings localeStrings1;
    private javax.swing.JLabel prix;
    private javax.swing.JTextField prixtxt;
    private javax.swing.JLabel salletxt;
    private javax.swing.JSpinner setupDateTime;
    private javax.swing.JTextField ticketsvendustxt;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateBn;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        FilmService fs = new FilmService();
        comboFilm.removeAllItems();
        for (Film f : fs.findAll()) {
            comboFilm.addItem(f);
        }

        SalleService ss = new SalleService();
        comboSalle.removeAllItems();
        for (Salle s : ss.findAll()) {
            comboSalle.addItem(s);
        }

    }

    private void vider() {
        if (comboFilm.getItemCount() > 0) {
            comboFilm.setSelectedIndex(0);
        }
        if (comboSalle.getItemCount() > 0) {
            comboSalle.setSelectedIndex(0);
        }
        setupDateTime.setValue(new java.util.Date());
        prixtxt.setText("");
        ticketsvendustxt.setText("");
    }
}
